name: brioche-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - picard=3.2.0
  - samtools=1.20
  - blast=2.16
  - moreutils=0.69
  - r-base=4.4.1
  - r-tidyverse=2.0.0
  - r-stringi=1.8.7
  - r-tidyselect=1.2.1
  - r-data.table=1.15.4
  - r-tidyr=1.3.1
  - r-dplyr=1.1.4
  - r-magrittr=2.0.3
